# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83114672506075ba4866194fe0160cde"
name = "cart-agent initial-release"
application_url = "https://app.abando.ai/embedded"
embedded = true
handle = "cart-agent-1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app.abando.ai/shopify/callback",
  "https://app.abando.ai/shopify/billing/return"
]

[pos]
embedded = false
